name: Build Site
on:
  push:
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build Site
        run: python build.py
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
